import { Section } from '../components/Section';
import { Math as InlineMath } from '../components/MathBlock';

export function S0_Introduction() {
  return (
    <Section
      id="introduction"
      title="About"
      subtitle="An interactive guide to understanding the WHIR protocol — the polynomial commitment scheme inside LeanMultisig."
    >
      <h3 id="about-this-visualizer" className="font-heading text-xl font-semibold text-text mb-3">
        About This Visualizer
      </h3>
      <p>
        This visualizer explains <strong>WHIR</strong> (Weights Help Improving Rate), the polynomial
        commitment scheme used inside <strong>LeanMultisig</strong> — a minimal zkVM designed to aggregate
        post-quantum hash-based signatures for Ethereum.
      </p>
      <p className="mt-3">
        Ethereum's consensus layer currently relies on BLS signatures for validator attestations.
        BLS is efficient and supports cheap aggregation, but it is vulnerable to quantum computers.
        The migration path leads to hash-based signatures like{' '}
        <a href="https://github.com/leanEthereum/leanSig" target="_blank" rel="noopener noreferrer" className="text-sienna hover:underline font-semibold">leanSig</a>,
        which are quantum-resistant but 10-100x larger than BLS and lack native aggregation. LeanMultisig is a
        minimal zkVM that aggregates thousands of these signatures into a single compact proof using
        a hash-based SNARK powered by WHIR.
      </p>
      <p className="mt-3">
        WHIR is the component that makes LeanMultisig's verifier fast enough for on-chain verification
        and recursive proof composition. Its super-fast verification time — hundreds of microseconds
        — is what enables a tree of recursive proofs to aggregate batches of leanSig signatures
        into one final proof that Ethereum validators can check cheaply.
      </p>
      <p className="mt-3">
        This site is an interactive, step-by-step guide that builds up the ideas behind WHIR from
        scratch. No prior knowledge of cryptography or zero-knowledge proofs is assumed — just a
        software engineering background.
      </p>

      <h3 id="how-demos-work" className="font-heading text-xl font-semibold text-text mt-10 mb-3">
        How the Interactive Demos Work
      </h3>
      <p>
        Throughout this site, interactive demos let you explore the math hands-on. To keep
        things readable, all demos operate over a small finite field rather than the large
        fields used in LeanMultisig's production implementation.
      </p>

      <div className="bg-bg-card border border-border rounded-lg p-5 my-6 space-y-4">
        <div>
          <div className="font-heading font-semibold text-sm text-text mb-1">
            Demo field: <InlineMath tex="\mathbb{F}_{17}" /> — Production field: KoalaBear prime
          </div>
          <p className="text-sm text-text-muted">
            The demos use <InlineMath tex="\mathbb{F}_{17}" /> (arithmetic modulo the
            prime <InlineMath tex="p = 17" />) for readability. In LeanMultisig, the field
            is the <strong>KoalaBear prime</strong>{' '}
            <InlineMath tex="p = 2^{31} - 2^{24} + 1" />, which fits in a single{' '}
            <code>u32</code> and enables an efficient Poseidon2 S-box via the cubing
            map <InlineMath tex="x \mapsto x^3" />. For 128-bit security in WHIR, LeanMultisig works
            over the degree-5 extension field <InlineMath tex="\mathbb{F}_{p^5}" />.
          </p>
        </div>

        <div>
          <div className="font-heading font-semibold text-sm text-text mb-1">
            Multiplicative subgroup and domain
          </div>
          <p className="text-sm text-text-muted">
            The multiplicative group of <InlineMath tex="\mathbb{F}_{17}^*" /> has order 16,
            generated by the primitive root <InlineMath tex="g = 3" /> (meaning{' '}
            <InlineMath tex="3^{16} \equiv 1 \pmod{17}" />). This gives us subgroups of size
            16, 8, 4, and 2 — perfect for demonstrating the repeated domain halving that WHIR
            relies on. The demos typically start with a domain of size 8 and fold down to 4,
            then 2. In LeanMultisig, the KoalaBear field has a much larger multiplicative group,
            enabling commitment domains of up to <InlineMath tex="2^{30}" /> elements.
          </p>
        </div>

        <div>
          <div className="font-heading font-semibold text-sm text-text mb-1">
            Polynomials
          </div>
          <p className="text-sm text-text-muted">
            Polynomials are represented in coefficient form over{' '}
            <InlineMath tex="\mathbb{F}_{17}" />. For example,{' '}
            <InlineMath tex="f(x) = 2 + 5x + 3x^2" /> has coefficients{' '}
            <InlineMath tex="[2, 5, 3]" /> and evaluations are computed via Horner's method.
            Multilinear polynomials (used in the sumcheck demos) are stored as their{' '}
            <InlineMath tex="2^m" /> evaluations over the boolean hypercube{' '}
            <InlineMath tex="\{0,1\}^m" />. In LeanMultisig, execution traces have up
            to <InlineMath tex="2^{25}" /> rows with 20 committed columns per cycle — these
            are encoded as multilinear polynomials and committed via WHIR.
          </p>
        </div>

        <div>
          <div className="font-heading font-semibold text-sm text-text mb-1">
            Pre-selected randomness
          </div>
          <p className="text-sm text-text-muted">
            In the real protocol, the verifier's challenges are random. In the demos, we use
            fixed "random" values so that the walkthrough is deterministic and reproducible.
            You can often adjust these values via sliders to see how different challenges
            affect the computation.
          </p>
        </div>
      </div>

      <div className="bg-bg-card border border-border rounded-lg p-5 mt-8">
        <h4 className="font-heading font-semibold text-base text-text mb-2">
          The Papers
        </h4>
        <p className="text-sm text-text-muted mb-2">
          <strong>WHIR</strong> was introduced by Gal Arnon, Alessandro Chiesa, Giacomo Fenzi, and
          Eylon Yogev in their 2024 paper{' '}
          <em>"WHIR: Reed-Solomon Proximity Testing with Super-Fast Verification"</em>.
          This visualizer is based on the protocol described in that paper.
        </p>
        <p className="text-sm text-text-muted">
          <strong>LeanMultisig</strong> is described in{' '}
          <em>"Minimal zkVM for Lean Ethereum"</em> (draft 0.6.0), which specifies how WHIR
          is used as the polynomial commitment scheme inside a minimal zkVM tailored for
          post-quantum signature aggregation on Ethereum.
        </p>
      </div>
    </Section>
  );
}
